### ISSUE TITLE
Allow for hiding side window to start

### ISSUE THREAD

**Issue by GitMurf** [GitMurf/roam-highlighter#10]
From Ivo V: I used it a few times so far and I'm happy with it. The only annoying thing is that clicking on the icon started to bring a pop-up with options. It was nicer without it. I understand that in some cases it's useful, but for me it just takes part of the screen and I have to click "hide" every time. It would be better if it's optional and configured in the extension settings. I would certainly use the highlighter more.

**Comment by GitMurf** [comment]
@Ivo Velitchkov makes sense and I was already debating that! I will update so it starts hidden, then can open with ctrl+S AND/Or if you click extension button twice on a Tab it will show it. What you think?

**Comment by GitMurf** [comment]
Or would you be okay with it if clicking Extension button twice hides it so since you prefer it hidden you could just by default double click extension button to start with it hidden? The reason I ask is that I’ve had a lot of folks talk about how much they love the window opening to start because then they know the highlighter is activated and working and “ready to go”.

**Comment by GitMurf** [comment]
Ok thanks for feedback! I’ll think about it because unfortunately I have to balance both sides of the argument ;) since many folks requested and love having window shown by default.but I hear you for sure.

I think the real solution is a chrome extension setting that is persistent that you can change/edit on whether to show the side window by default or not. I haven’t worked with extension options before but I’m sure it’s easy. What you think about that? I’ll leave the default to show the window but you can change the extension option once to say hide by default and then it will always hide for you. Does that sound ok?

**Comment by tclaiborne** [comment]
+1 to offering a setting to not show the window. On my current device, the window overlaps the content, which makes it hard to read. I guess if it was narrower that I would also help.
