### ISSUE TITLE
Auto start option for extension so don’t have to click button

### ISSUE THREAD

**Issue by GitMurf** [GitMurf/roam-highlighter#13]
To your second point that one is a bit more sensitive. Since I’m messing with the clipboard and binding to a key like ctrl+X I don’t want to auto start the extension on every tab because I can hear it now “my ctrl+x is broken on websites after installing extension when I didn’t want to run it. How do I turn it off?” So that one is more dangerous.

I’ll dig around and see if there is a good way to give the user an option to auto start or not without me needing to change the overall code/structure too much. Fair enough?

**Comment by lkhphuc** [comment]
How about customizable keyboard shortcuts?
For me on MacOS with Firefox, the Cmd+S is used for "save web page" (who does it anyway), and it cann't be override.
I'm not sure about Chrome but in Firefox the shortcut for extension can be configured like so.
<img width="958" alt="Screenshot 2020-05-17 at 12 23 32" src="https://user-images.githubusercontent.com/12573521/82143098-3bad6a80-9839-11ea-97b9-9ce1f7504daa.png">

**Comment by GitMurf** [comment]
> How about customizable keyboard shortcuts?
> 
> For me on MacOS with Firefox, the Cmd+S is used for "save web page" (who does it anyway), and it cann't be override.
> 

@lkhphuc it is supposed to override the default “save page” action. And I purposely picked that shortcut cuz as you said no one uses that and it also is “s” for “show” or “settings” so easy to remember. You have tried it and it is still trying to save the web page? Can you please take a GIF / screen recording and show me it happening? Thanks. 

@sai-prasanna has the shortcut worked fine for you? Or you also not able to get over default save page with the + S shortcut?

Is this maybe a Mac thing? I’m on Windows.

**Comment by GitMurf** [comment]
> How about customizable keyboard shortcuts?
> 
> For me on MacOS with Firefox, the Cmd+S is used for "save web page" (who does it anyway), and it cann't be override.

@lkhphuc i see the problem. My binding for this one is actually the ctrl key on Mac too. So actually use control + S not command. I’ll fix and add command as option too. On my wife’s Mac it seems the first time you may have to press ctrl+S twice for some reason.

**Comment by GitMurf** [comment]
@lkhphuc ok I just updated the Firefox extension so now either Ctrl + S or Command + S should work. Can you uninstall current extension and then re-download and install and tell me if Command + S now works instead of the Webpage Save? Thanks!

https://github.com/GitMurf/roam-highlighter/blob/master/Firefox%20temp%20Add-on/roam_highlighter-1.8-fx.xpi

GitHub page > click "Download" > choose "Open" and select "Firefox" to open with (for Windows at least). Or open Firefox and go to Menu and "Open file".

**Comment by lkhphuc** [comment]
Thank you. It work now after I click the little icon.
Only problem is the cut function Cmd+X is overided but I guess this is your design as, Ctrl-X also override cutting in Windows.

One minor detail is that it would be better if we can move all the shortcut to use the same modifier key though. Currently we're having Ctrl+Q, Cmd+X, Cmd/Ctrl+S. As `Cmd+...` are mapped to all sort of things by default in Mac, Ctrl is probably the best option.

**Comment by GitMurf** [comment]
@lkhphuc thanks for the feedback! As for "Cut" we have no option because the way browsers work, to access the clipboard with javascript you have to initiate a cut, copy or paste event otherwise the browser thinks the code is potentially melicious and doesnt want random code to access the clipboard without the user initiating it with a clipboard type event/shortcut. Does that make sense? And the "cut" command would hardly ever need to be used on a website... other than maybe in a form you are filling out, but even then, just use "copy" and then delete the text as if was "cut". Make sense?

To the other point about modifier keys... the problem with Ctrl is that with Macs that initiates the rickt-click menu when combined with Click. I originally did have everything Ctrl and it didn't work for Mac users. And "cut" is command key anyways for Macs so that would be different. To be honest since I'm a windows guy, and because it isn't as "complicated" as Mac keys, things are built Windows first, Mac second because also I dont have a Mac so testing is hard... i have to try on my wife's computer when needed haha. So with Windows everything is the Ctrl key. Mac it has to be a little less consistent. Make sense?

If you have some thoughts on what would be best for Macs I have no problem adding/changing things for Macs that would make sense, so let me know.

**Comment by lkhphuc** [comment]
Ah, the Cmd+X makes sense now. Thanks a lot.
