### ISSUE TITLE
Feature idea: Create a custom template to export the notes

### ISSUE THREAD

**Issue by squiter** [GitMurf/roam-highlighter#139]
One thing that I'm missing in the extension is the option to customize how it'll generate the blocks. In my scenario, as an example, I like to put everything that I just copied from a site, or highlighted on a book, inside a quote block `[[>]]` to make it explicit that I'm coping this content from someone else.

If we could create a custom template to generate those blocks it'll solve that problem.

**Comment by GitMurf** [comment]
@squiter sorry for the slow response. Do you mean basically a way to prepend each highlight with a certain character(s)/string? So for example instead of the following:

```
- highlight 1
- highlight 2
- highlight 3
```

You would instead have the following:

```
- [[>]] highlight 1
- [[>]] highlight 2
- [[>]] highlight 3
```

Do I understand your request correctly?

**Comment by GitMurf** [comment]
Actually @squiter if this is indeed what you are looking for, you can already do this! :-) It isn't the most elegant solution but just change the "bullet" setting. See video below. Does this give you what you want?

https://user-images.githubusercontent.com/64155612/158474802-2e8cdd91-96b8-40ca-b382-22194a327e47.mp4

**Comment by squiter** [comment]
Yeah, it's exactly that! I figure out and I'm already using it! I forgot to update here! 
Anyway thanks \o

**Comment by GitMurf** [comment]
> Yeah, it's exactly that! I figure out and I'm already using it! I forgot to update here! Anyway thanks \o

Sweet! Glad to hear! My docs aren't the greatest in the world and my YouTube video tutorials you can barely hear the audio 🤣 ... one day I will improve all of that, but just have to find the time!

Curious... are you still using the Highlighter much? I'm always curious if people stick with my Extension or if just install it and then don't use it much after a while :)

**Comment by squiter** [comment]
Yeah man, I use it almost every day! :D
I like to bring highlights to my notes before going deeper into each quote to build an argument or just to think deeply about it and your extension helps me a lot in this process

**Comment by GitMurf** [comment]
> Yeah man, I use it almost every day! :D I like to bring highlights to my notes before going deeper into each quote to build an argument or just to think deeply about it and your extension helps me a lot in this process

Great to hear!
