### ISSUE TITLE
Firefox extension manual install

### ISSUE THREAD

**Issue by GitMurf** [GitMurf/roam-highlighter#14]
Firefox extension/add-on is ready to go but just got this from Mozilla... they won't approve my highlighter extension until Roam is public or Open Beta! Lame!

![image](https://user-images.githubusercontent.com/64155612/82151408-6fc06580-9810-11ea-920e-a017bd47985a.jpeg)

Since Firefox won't let us upload a public add-on until Roam is open Beta, I created a private add-on you have to download directly. Here is the link.

https://github.com/GitMurf/roam-highlighter/blob/master/Firefox%20temp%20Add-on/roam_highlighter-1.8-fx.xpi

Go to that GitHub page, click "Download" and then choose to "Open" and choose "Firefox" as the program to open with (this is at least from a Windows perspective). It should install the Add-on for you. Let me know if you have any issues.

**Comment by aleksandar-todorovic** [comment]
Pardon my ignorance, but isn't Roam in open beta right now? 

I can go to the website and click on "sign up". I don't see any mention of the wait list.
