### ISSUE TITLE
highlights don't persist when browser closed/reopened

### ISSUE THREAD

**Issue by perfectlyGoodInk** [GitMurf/roam-highlighter#141]
When I highlight a page and then close the browser (either Opera or Chrome) and reopen, the highlights on the page appear to be lost (and yes, I am enabling the extension with Alt-X when I go back to the page).

If this is a feature that has not yet been implemented, I would recommend documenting this clearly so that users know to save their highlights before closing the browser (fortunately, I did not lose much work because I am only testing this as a possible replacement to Weava, which has been unreliable for me).

But one of my main uses of a web highlighter is to help analyze longer articles which I will often not be able to read in one sitting. The highlights both help me review what I have already read as well as quickly find where I had left off. I would imagine this to be a fairly common use case.

**Comment by GitMurf** [comment]
Sorry but this is not a feature. I will try to document that better but this is for note taking and copying your highlights into a note taking tool like Roam or Obsidian or OneNote etc.
