### ISSUE TITLE
Feature request: save settings

### ISSUE THREAD

**Issue by tfiers** [GitMurf/roam-highlighter#15]
Settings like the added tag or how to handle line breaks could be saved across tabs & sessions, so you don't have to re-input them for every new webpage.

Btw, great ideas in this plugin.

**Comment by GitMurf** [comment]
@tfiers thanks for the input and for officially opening an Issue in Github! That really helps.

To your request, already in the works and hopefully in the next 1-2 days will have it updated! Keep posting new ideas as they come. Thanks!

**Comment by GitMurf** [comment]
@tfiers can you please confirm it auto updated for you and that it now saves like you requested? Any other features/changes you’d like to see? Thanks!

**Comment by tfiers** [comment]
It works as imagined now, thank you!
