### ISSUE TITLE
Remove formatting tags?

### ISSUE THREAD

**Issue by royYYZSFO** [GitMurf/roam-highlighter#16]
I opened [this link](https://news.airbnb.com/a-message-from-co-founder-and-ceo-brian-chesky/) in GetPocket. When I highlighted, this is what I got in the sidebar. It would be great to remove the HTML formatting tags otherwise it's impossible to use the extension. Thanks!

Here's what it looks like - https://share.getcloudapp.com/2NuXDnGZ

<ul>
	<li>[Pocket - A Message from Co-Founder and CEO Brian Chesky](https://app.getpocket.com/read/2973631977) #[[Roam-Highlights]]
<ul>
	<li>__would have to go further when we faced two hard truths:__
<li>
	<li>__We don’t know exactly when travel will return.__
<li>
	<li>__When travel does return, it will look different.__
<li>
	<li>__While we know Airbnb’s business will fully recover, the changes it will undergo are not temporary or short-lived. Because of this, we need to make more [[[[[[fundamental]]]]]] changes to Airbnb by reducing the size of our workforce around a more focused business strategy.__
<li>
</ul>
<li>
</ul>

**Comment by GitMurf** [comment]
@royYYZSFO I don’t understand your issue/request. I’m happy to fix/improve it asap but need more clarity on what you think the problem is? Thanks!

**Comment by royYYZSFO** [comment]
If you see in the image, the copying includes the HTML markup like <ul> </ul> <li> , etc….

https://share.getcloudapp.com/2NuXDnGZ

Ideally, it would be stripped of all of that markup so I'm just left with the text the way it looks in the page I was reading:

https://share.getcloudapp.com/xQuW2eAL

Thanks!

**
*
*Roy Raanani*

*
tel: +1 (415) 568-5718

**Comment by GitMurf** [comment]
@royYYZSFO ok now I understand the confusion! You must not have been auto updated yet! I removed the HTML the other day in the new version. Now there is a checkbox where you can choose to see the HTML if you have a reason (mainly for me when I'm testing stuff) but sometimes people may want HTML for website purposes. But by default it should only be showing the plain text without the HTML.

![image](https://user-images.githubusercontent.com/64155612/82633134-38a2d900-9baf-11ea-8642-79a9182cbf09.png)


## When you startup the highlighter it should now tell you what version you are on (see screenshot below). Are you on v1.9.2?

![image](https://user-images.githubusercontent.com/64155612/82633184-596b2e80-9baf-11ea-8e27-8af1d8518bd1.png)
