### ISSUE TITLE
Add default copy [page title](URL) when losing extension from button click

### ISSUE THREAD

**Issue by GitMurf** [GitMurf/roam-highlighter#19]
From Ivo:

Wish: There is just one thing I would really love to have and it's the one I would surely use the most: the current "Copy Page Title & URL" feature to work directly, without clicking on the extension icon first. I can't overstate how useful this would be. 95% I just need the URL in []() and 5% - highlights. I guess this is the case with most people but I might be wrong.

**Comment by GitMurf** [comment]
RE: Wish: so if you don’t click the extension button, then I’d have to have the script loaded by default which I don’t want to do for the full thing without user explicitly turning it on because I can’t have the “cut” command always hijacked by my extension by default on every page. But I could partially load just the page title URL link like you said but it has to be binded to some user action. So what would you like it to be? You have to do something to initiate the command to add that to the clipboard. So what would you like it to be?

Any shortcut, e.g. Ctrl+Z. so that Ctrl+Z, X would do the whole thing.

But remember with this request every tab 100% of the time would be binded to Ctrl+Z so you could then NEVER use an Undo function on the Web because always taken by my highlighter. I don’t think that is reasonable for users. Thoughts? Also, just to be honest, it sounds like you are willing to press a key combo to get the Page/URL but you just aren’t willing to use the mouse to Click the extension button? Because what I could do is by default copy page title / URL to clipboard when you press the highlighter extension button... but sounds like that isn’t sufficient because you don’t want to have to use the mouse? Am I understanding correctly?

I do understand the appeal to no mouse and I try to use mouse as little as possible. But if you go to a webpage and want the link, one single click of the extension button to me seems like a fine workflow to get the page title / URL. And since the settings save now If you have the side window hidden already it will never show until you do Ctrl/command + S or click extension button twice since it shows/hides as well. Does that make sense? Is that still unreasonable from your workflow perspective?

But I can certainly add (and it is a good idea) to by default copy the page title / URL to clipboard on clicking on extension button. Would you use that? I agree I often just want the link of a page in Roam format and don’t want/need highlights so that would be useful.

Yes, it definitely would. My previous alternative was to use Copy2Roam which requires every time to toggle bookmarks toolbar which I prefer to keep it hidden.

In fact, that would be perfect. I'm very much looking forward to it.

**Comment by tfiers** [comment]
Easier acces to copying just page title/URL (without hightlights) would be great indeed.

Current way to do this is:

1. activate plugin (which I have bound to a keyboard shortcut)
2. click on webpage again
3. ctrl-x

It would be great if the plugin already automatically copied page title/URL to clipboard when the plugin is activated (i.e. at step 1 above)

**Comment by GitMurf** [comment]
Implemented and will be included whenever the Chrome store publishes update and auto updates :-) Should be within next 12 hours or so. When you see v1.9.3 loaded in the side window message at startup of extension you'll know it should be working.
