### ISSUE TITLE
Settings are not visible on IE Edge browser

### ISSUE THREAD

**Issue by eBerdnA** [GitMurf/roam-highlighter#22]
I'm using the extension in Microsoft Edge (Chromium) and can't open respectively can't the settings. If I try to open them the content is moved to the left but no settings are display as you can see from the following screenshot.

![image](https://user-images.githubusercontent.com/2204092/82668417-fd012100-9c39-11ea-9641-10ea6a2ff882.png)

**Comment by GitMurf** [comment]
@eBerdnA I know it isn't an answer you want to hear, but right now only supported for Firefox and Chrome. I have done zero testing on IE/Edge but I am definitely keeping an eye on this and will let you know when I have time to look into testing on Edge. Just not enough users on that browser to justify spending time right now on that versus fixing the current issues with the Extension. Hope you understand! Will try to get to it in the next week.

**Comment by eBerdnA** [comment]
Fair enough.
Nevertheless I'm still confused why this extension does behave different in Chrome and MS Edge (Chromium) which I have just checked myself.

All other extensions in MS Edge work without any difference even though I installed them using the Chrome Web Store.
