### ISSUE TITLE
Settings side window with wrong width

### ISSUE THREAD

**Issue by vitalwarley** [GitMurf/roam-highlighter#30]
Hello,

First of all, thank you for this great tool! 

I am only using for a day. Yesterday I didn't find anything wrong. However, today I noticed this bug in the side window:

![Peek 28-05-2020 11-42](https://user-images.githubusercontent.com/6365065/83157341-ddef0d00-a0d9-11ea-92d0-2680f4859996.gif)

After recording it, I reinstalled the extension: same problem. I also tried in Chromium: no luck.

This is a minor thing, but I think you should know.

Thanks again and let me know if there is any info you need from here.

**Comment by GitMurf** [comment]
@vitalwarley thank you for raising this issue and for the detailed GIF that helped me see the exact problem! I have it fixed and it will be updated in next release hopefully tonight (v1.9.7).

Can you confirm this "glitch" only happened on this webpage? Or at least on just a few and that most other web pages did not have this issue? I believe it has to do with how that webpage is doing HTML and CSS. Either way I have it fixed but curious to know if you saw same problem elsewhere? Thanks!

**Comment by GitMurf** [comment]
Link to the website with the issue for historical testing purposes: http://augmentingcognition.com/ltm.html

**Comment by vitalwarley** [comment]
> Can you confirm this "glitch" only happened on this webpage? Or at least on just a few and that most other web pages did not have this issue? I believe it has to do with how that webpage is doing HTML and CSS. 

I have tried in some different webpages here (~10) and the results I got were mostly 50/50. I think you're right, that it has to do with how the webpages manage its HTML and CSS.

Thanks for the fix!

**Comment by GitMurf** [comment]
@vitalwarley finished the update and submitted to chrome store. Now just have to wait for them to confirm/finish the review. Usually takes 6-12 hours. As soon as the extension shows v1.9.7 then it should be fixed. Once it has updated and is working for you please comment back here so I can close out the "Issue". Thanks!

**Comment by vitalwarley** [comment]
@GitMurf thank you. Everything is working fine now :)
