### ISSUE TITLE
Default setup

### ISSUE THREAD

**Issue by Aushotshot** [GitMurf/roam-highlighter#31]
Hi Murf - highlighter is good - great job.

Is there a way for me to configure so I can paste - this - by default - so that I don't have to go and delete it for each copy...
[Rom 2:12 NIV - All who sin apart from the law will - Bible Gateway](https://www.biblegateway.com/passage/?search=Rom+2%3A12&version=NIV)

as this: [Rom 2:12](https://www.biblegateway.com/passage/?search=Rom+2%3A12&version=NIV)

So without " NIV - All who sin apart from the law will - Bible Gateway "

Thanks Mate - (go to write mode to see my issue)

**Comment by GitMurf** [comment]
@Aushotshot what do you mean “go to write mode to see my issue”?

To answer your question, your issue actually gave me a great idea. Often a page title has a Dash as a separator just like yours does. I can add checkbox to settings that defaults to using page title up to the first dash which would give you what you want. Will add to my to do list.

**Comment by GitMurf** [comment]
Well it wouldn’t give you exactly what you want but close. The NIV would still be there. But that is all I can do to automate your request. Otherwise I’d have to hardcore this in for your specific website and I can’t do that for everyone / every site. Hopefully my proposed workaround would be sufficient.

**Comment by Aushotshot** [comment]
That's perfect Murf - never been on Github before -so (go to write...) was the markup view - ... :-) silly me!

**Comment by GitMurf** [comment]
@Aushotshot finished the update and submitted to chrome store. Now just have to wait for them to confirm/finish the review. Usually takes 6-12 hours. As soon as the extension shows v1.9.7 then you should be able to use the new "truncate" option next to page title to shorten it to what you want. Once it has updated and is working for you please comment back here so I can close out the "Issue". Thanks!

**Comment by Aushotshot** [comment]
Murf it's great!  Thank-you.

**Comment by Aushotshot** [comment]
I manage to get all the blurb out by truncating at "N" - do no editing after paste.  Great outcome.  Thanks for your efforts.
[Gen 4:16](https://www.biblegateway.com/passage/?search=Gen+4%3A16&version=NIV)
