### ISSUE TITLE
Option to remove external links

### ISSUE THREAD

**Issue by mrcasals** [GitMurf/roam-highlighter#32]
Hi!

Is there any way to add an option to remove external links? Sometimes they're not meaningful, and removing them takes some manual work...

Thanks!

**Comment by GitMurf** [comment]
@mrcasals do you mean the very top link I add of the webpage your highlighting from? Or do you mean links from within the stuff you’re highlighting?

**Comment by mrcasals** [comment]
Sorry, I meant the links within the highlighted text!

**Comment by GitMurf** [comment]
@mrcasals interesting idea.... haven't had that request before. I'll put it on my list. What would you like done to the links? Just removed and blank/empty text in its place? Put a placeholder like [LINK] in its place to show where a link was removed? Or what other thoughts/ideas? How would you like it handled?

**Comment by mrcasals** [comment]
My use case is highlighting sections of a Wikipedia article. Sometimes these articles are filled with links to other articles. While that's fine for the general use case, I guess, I get the feeling that these external links distract me on Notion, so I remove the link, keeping the text. 

The highlighter converts links to markdown, check this simple example:

```
- [Choquequirao - Wikiwand](https://www.wikiwand.com/en/Choquequirao) #[[Roam-Highlights]]
	- The site is reached by a two-day hike from outside [Cusco](https://www.wikiwand.com/en/Cusco)
```

My request is an option to remove the Markdown links _within_ the highlighted text (note how the title one stays put):

```
- [Choquequirao - Wikiwand](https://www.wikiwand.com/en/Choquequirao) #[[Roam-Highlights]]
	- The site is reached by a two-day hike from outside Cusco
```

Would that make sense? If you think it's out of the scope I can try to use some tool to remove them, or keep removing them manually 😄 Also, we can try to gather more feedback, if I'm the only one with this issue I can try to work around it!

**Comment by GitMurf** [comment]
Ok gotcha. Makes more sense now. I thought you were more worried about links that weren’t in markdown already. Like “You should visit www.espn.com if you want more info on sports.”

In this case though, what would you want because www.espn.com will show up as a link in Roam by default.

**Comment by mrcasals** [comment]
If the text contains a URL directly like in this case I'd leave it as it is, and if Roam detects this as a link then that's OK

**Comment by GitMurf** [comment]
Closed the following two issues and marked as duplicates of this one: #38 and #43

**Comment by GitMurf** [comment]
from Issue #38 on June 24th:

Hey man! Lovely plugin. Been using it with Obsidian for a while Now.

I use it to take notes off Wikipedia articles. It would be helpful if you could add the feature to turn off links. I would prefer not to have links in my note that arent added by me - I usually take notes off webpages and I will have to manually delete links from extracts - this takes a lot of time.

Thanks and regards!

**Comment by GitMurf** [comment]
from Issue #38 (Option to Hide links) on June 19th:

Your plugin is amazing!! Thank you sir/Madam

I've been using it a lot. however one thing that troubles me is that when I am using it to selectively read of Wikipedia, I end up lifting links that I do not want. And so I end up editing the copy pasted page to remove links.
If only there was a way to turn off this feature!

**Comment by GitMurf** [comment]
@mrcasals finally got around to this! Chrome should approve and auto update the extension in the next day or two. Look for v1.9.8 and you'll know it is there :)

Please let me know if I hit the mark here or still not quite there? See GIF demo below.


![GSfeI4CxJ6](https://user-images.githubusercontent.com/64155612/96808164-28489180-13cd-11eb-93c3-af6ed1bc9b73.gif)

**Comment by GitMurf** [comment]
Added new issue #83 as follow-up to fixing this.

**Comment by GitMurf** [comment]
@mrcasals update is out! Check it out and let me know if I hit the mark? Thanks!
