### ISSUE TITLE
Feature to be able to access PDF files on browser and highlight them.

### ISSUE THREAD

**Issue by shrvenkataraman** [GitMurf/roam-highlighter#35]
On browser, open pdf files, and highlight the content in those files - extract as obsidian or roam formatted text. This should be possible (hypothes.is does something similar).

**Comment by aviekakkar** [comment]
+1 for this! pleasee

**Comment by ccpalmer** [comment]
+1 - just spent an hour trying to figure out why this wasn't working.  This is a key capability for research.

**Comment by rongmere** [comment]
+1

**Comment by GitMurf** [comment]
I hear you all and wish I could say I can implement this but PDF highlighting requires a lot of different code and fundamental approach to accomplish. It is not something I plan to do unfortunately.

Appreciate the input/feedback though.
