### ISSUE TITLE
Option to Hide links

### ISSUE THREAD

**Issue by K-293** [GitMurf/roam-highlighter#38]
Your plugin is amazing!! Thank you sir/Madam

I've been using it a lot. however one thing that troubles me is that when I am using it to selectively read of Wikipedia, I end up lifting links that I do not want. And so I end up editing the copy pasted page to remove links. 
If only there was a way to turn off this feature!

**Comment by GitMurf** [comment]
@K-293 so do you mean a setting that will remove all links from highlights on a page? If a link is [page name](URL) do you want it replaced with just Page Name? Or do you want it to be replaced with [Page Name]? Or do you want it just to remove page name / URL all together and show nothing in its place?

**Comment by GitMurf** [comment]
@K-293 someone requested something similar I think. Can you checkout this request and let me know if you want the same thing?


https://github.com/GitMurf/roam-highlighter/issues/32

**Comment by GitMurf** [comment]
Duplicate of #32

**Comment by GitMurf** [comment]
Duplicate of #32

**Comment by GitMurf** [comment]
@K-293 update is out! Check it out and let me know if I hit the mark? Thanks!
