### ISSUE TITLE
Line break issues with The Atlantic

### ISSUE THREAD

**Issue by GitMurf** [GitMurf/roam-highlighter#45]
https://roamresearch.slack.com/archives/G013D2T1SSG/p1594037382477200

https://www.theatlantic.com/politics/archive/2020/07/white-evangelicals-black-lives-matter/613738/

@ Murf The Atlantic gives consistent line- or paragraph-breaks just before mid-sentence links:

![image](https://user-images.githubusercontent.com/64155612/86596321-dd565b80-bf4e-11ea-84ac-8f8d77e55e9c.jpeg)

**Comment by Murf** [comment]
You mean @GitMurf not @Murf

**Comment by GitMurf** [comment]
> You mean @GitMurf not @Murf 

Sorry didn’t mean to @ anyone. Was copy/pasted from Slack where someone @ me as my slack name there is Murf :)

**Comment by GitMurf** [comment]
Duplicate of #50

**Comment by Murf** [comment]
wrong Murf again
