### ISSUE TITLE
Mouse Click Highlight not working

### ISSUE THREAD

**Issue by david-ps** [GitMurf/roam-highlighter#48]
Just installed latest Chrome Extension 1.9.7.2 
Can only highlight using Crtl-X, 
Mouse/cursor does not highlight ie no yellow and no copy to sidebar. 
Have tried on Chrome and Edge latest versions.

**Comment by GitMurf** [comment]
Auto highlight by mouse drag is not a feature of my highlighter... yet. Right now ctrl+X is only option.

**Comment by GitMurf** [comment]
Duplicate of #71

**Comment by GitMurf** [comment]
@david-ps it has been implemented! Please check out the new update and let me know what you think? Thanks!
