### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by DutchPete** [GitMurf/roam-highlighter#49]
Hi, I have RH installed in Chromium for use with Obsidian. I did something stupid: I clicked on the black button "clear all highlights".

I tried to undo with CTRL+Z but nothing happened. I am afraid you'll tell me they're lost forever, but I am hoping there is a way to recover them. Is there?

**Comment by GitMurf** [comment]
@DutchPete i am sorry to hear that. But unfortunately yes there is no way to recover. The way it works with the HTML source code behind the scenes there is no way to implement an undo :( I know that's not the answer you want to hear. I am very sorry.

**Comment by DutchPete** [comment]
OK, I understand, it's not your fault, I was stupid enough not to think it through properly what clicking on that button could/would mean.

I look at it on the bright side: the only way to learn is to make mistakes. Every cloud has its silver lining.
