### ISSUE TITLE
Can not use on the local storage PDF 

### ISSUE THREAD

**Issue by rongmere** [GitMurf/roam-highlighter#52]
Hi, 
If it can be used to read the papers which store on my computer, it will be much more useful.

As I know, we can use the chrome open the local storage PDF  but can not use Roma HightLighter which can not catch the information without online (HTML). 
Also, Weava Highlight can do that it turns paper online.

My Email: 573637109@qq.com

**Comment by GitMurf** [comment]
Sorry but PDF highlighting requires a lot of different code and fundamental approach to accomplish. It is not something I plan to do unfortunately.
