### ISSUE TITLE
Anomalous behavior in Roam with Roam-Highlighter installd 

### ISSUE THREAD

**Issue by eatondpe** [GitMurf/roam-highlighter#56]
I've been forced to disable Roam-Highlighter due to the following interesting behaviors that occur only when Roam-Highlighter is active.

1. Pressing ctrl-v pastes text into Roam. But when Roam-Highlighter is active, it pastes that text someplace other than where the cursor is. Often, it will paste text at the beginning of the block under the cursor, rather than at the insert location.

2. Pasting text, using ctrl-v, pastes text as described above, but also includes a new block, `estimates(0)`, at the end of the current page.

Both of these occur only when Roam-Highlighter is active. Disabling Roam-Highlighter restores expected behavior.

I use Microsoft's Edge-chromium browser on a Windows 10 laptop.

**Comment by GitMurf** [comment]
@eatondpe sorry to hear that! Unfortunately I do not use Edge browser. It was much harder to build for all browsers but chrome/firefox seemed to be two the most similar and also the two most popular browsers. If you want to try Chrome browser you should not have those problems.
