### ISSUE TITLE
using roam-highlighter with Evernote Web

### ISSUE THREAD

**Issue by jasonromney** [GitMurf/roam-highlighter#58]
I'm wondering if it is possible to use roam-highlighter while an Evernote Web note is open for editing in a Chrome window please? I'm finding that if I highlight text in the Evernote note, and type Command-X to highlight it using roam-highlighter, the text is deleted instead of being yellow highlighted. Use of roam-highlighter in a Chrome window with a normal web page works fine. Thanks in advance for any suggestions or workarounds.

**Comment by GitMurf** [comment]
@jasonromney this is unfortunately an issue where Evernote "over rules" my highlighter as they have priority on the Clipboard events :-(
