### ISSUE TITLE
Kindle Highlights button does not appear in Settings pane

### ISSUE THREAD

**Issue by lwrogersjr** [GitMurf/roam-highlighter#61]
1. Browse to read.amazon.com.
2. Click "Show notes and marks" button in the Kindle web toolbar.
3. Kindle web page displays book highlights in a simulated modal dialog ([KindleWebReader.pdf](https://github.com/GitMurf/roam-highlighter/files/5250578/KindleWebReader.pdf)), unlike the way it appears in the Roam Highlighter demo.
4. Open Roam Highlighter Settings.
5. Kindle Highlights button does not appear in the Settings pane ([RoamHighlighterSettings.pdf](https://github.com/GitMurf/roam-highlighter/files/5250580/RoamHighlighterSettings.pdf)).

I love Roam Highlighter! Thanks!

**Comment by GitMurf** [comment]
From Ivo on Aug 19th
I don't see anymore the Kindle Highlight button

![image](https://user-images.githubusercontent.com/64155612/93896746-26908e80-fca6-11ea-8ee0-69cd96def936.png)

**Comment by GitMurf** [comment]
@lwrogersjr it is kind of "touchy" but you need to go directly to https://read.amazon.com/notebook

An important note, which I think was potentially Ivo's issue, is that if you are not currently logged in to Amazon and it asks you to login when you go to https://read.amazon.com/notebook then it appears it takes you to a bit of a different URL which Roam highlighter does not recognize and therefore doesn't show the Kindle extract options / buttons.

The solution is to simply click the link again in Roam Highlighter settings and then you should be good to go! See screenshot and GIF below for more details.

@lwrogersjr  please confirm it is working as expected so I can close the issue. Thanks!

![image](https://user-images.githubusercontent.com/64155612/93897125-90109d00-fca6-11ea-8802-7d76b5c69c4a.png)

![Upm7XymT8p](https://user-images.githubusercontent.com/64155612/93897269-bc2c1e00-fca6-11ea-8e88-e1833013aa25.gif)

**Comment by GitMurf** [comment]
Just opened a new Issue #63 to account for the issue of Roam Highlighter not recognizing the link Amazon takes you to after initial login.

**Comment by lwrogersjr** [comment]
Yes, Kindle Highlights works great for https://read.amazon.com/notebook.

Thanks!

**Comment by clement-moulin-frier** [comment]
Hi,

It seems there is an issue for non-US amazon accounts though. For instance in France, the URL is https://lire.amazon.fr/notebook ("lire" means "read", you get it)
I don't see the Kindle Highlights button, I guess that it is because that URL is not recognized.
Unfortunately I don't have access to my books if I log to read.amazon.com (probably to book copyright restrictions in other countries)

Any hint on how to solve it?

(thanks for the great extension, I'm using it a lot!)

**Comment by GitMurf** [comment]
> Hi,
> 
> It seems there is an issue for non-US amazon accounts though. For instance in France, the URL is https://lire.amazon.fr/notebook ("lire" means "read", you get it)
> I don't see the Kindle Highlights button, I guess that it is because that URL is not recognized.
> Unfortunately I don't have access to my books if I log to read.amazon.com (probably to book copyright restrictions in other countries)
> 
> Any hint on how to solve it?
> 
> (thanks for the great extension, I'm using it a lot!)

@clement-moulin-frier I will be tracking this now in Issue #63 as others have reported similar issues.
