### ISSUE TITLE
Subscript creates new blocks

### ISSUE THREAD

**Issue by kvistgaard** [GitMurf/roam-highlighter#69]
Highlighting from [that article](https://www.novusbio.com/support/general-support/antibody-basics.html#:~:text=Antibodies recognize foreign invading microorganisms,that elicits an immune response.) this text:

> All antibodies share the same basic structure which consists of four polypeptide chains, two light chains (L chains) and two heavy chains (H chains), held together by disulfide bonds. These four polypeptide chains form a symmetrical molecule commonly depicted as having a "Y" shape and comprised of two identical halves, each bearing identical antigen binding sites.  Based on amino acid sequence variability, two main regions (variable and constant) are identifiable within each antibody polypeptide chain. These regions are commonly depicted as variable light (VL), constant light (CL), variable heavy (VH), and constant heavy (CH). Antibodies differ the most in their amino acid sequence at their variable regions which underscore their antigen specificity. Antigen binding sites are formed from the amino terminals or variable regions of the heavy (VH) and light (VL) chains.

Creates

> - All antibodies share the same basic structure which consists of four polypeptide chains, two light chains (L chains) and two heavy chains (H chains), held together by disulfide bonds. These four polypeptide chains form a symmetrical molecule commonly depicted as having a "Y" shape and comprised of two identical halves, each bearing identical antigen binding sites. Based on amino acid sequence variability, two main regions (variable and constant) are identifiable within each antibody polypeptide chain. These regions are commonly depicted as variable light (V
> - L
> - ), constant light (C
> - L
> - ), variable heavy (V
> - H
> - ), and constant heavy (C
> - H
> - ). Antibodies differ the most in their amino acid sequence at their variable regions which underscore their antigen specificity. Antigen binding sites are formed from the amino terminals or variable regions of the heavy (V
> - H
> - ) and light (V
> - L
> - ) chains.

**Comment by GitMurf** [comment]
@kvistgaard finally got around to this! Chrome should approve and auto update the extension in the next day or two. Look for v1.9.8 and you'll know it is there :) Please confirm that the issue is resolved once you have a chance to test it. Thanks!

![i5iuOQ3bwP](https://user-images.githubusercontent.com/64155612/96823285-fe00cf00-13e0-11eb-9808-7203eea80e15.gif)

**Comment by kvistgaard** [comment]
I force-updated but it is still 1.9.7.2

**Comment by GitMurf** [comment]
@kvistgaard still finishing up the release. Will let you know when it is published. Thanks!
