### ISSUE TITLE
Way to highlight just by dragging over words?

### ISSUE THREAD

**Issue by noamsiegel** [GitMurf/roam-highlighter#71]
Not an issue, but would be a lovely feature! Hitting "Command + X" is repetitive and redundant after a few hundred times. But all in all, a great extension, and am I am eagerly waiting to see where this goes.

**Comment by GitMurf** [comment]
Merged #48 to this issue

**Comment by GitMurf** [comment]
Merged #20 to this issue:
> Ok I’ll implement the auto highlight option into the settings so you can choose to highlight on selection without needing to use Ctrl+X. Does that sound good?
Add setting / option to highlight by default and do NOT need ctrl+X

**Comment by GitMurf** [comment]
![aJLwEFtall](https://user-images.githubusercontent.com/64155612/97540472-ea291000-1980-11eb-9cc7-a7e0b96376c0.gif)

**Comment by GitMurf** [comment]
@noamsiegel it has been implemented! Please check out the new update and let me know what you think? Thanks!

**Comment by noamsiegel** [comment]
@GitMurf it works perfectly. Thank you for all the work!
