### ISSUE TITLE
Kindle Notebook page not recognized

### ISSUE THREAD

**Issue by mattwien** [GitMurf/roam-highlighter#72]
When I go to the settings page and klick on Kindle Notes & Highlights Amazon shows me my Highlights correctly. 
But when I chose "get Kindle highlights" I get a messagebox telling me: 
Not on kindle page. Go to: https://read.amazon.com/notebook

The page I'm on is https://read.amazon.com/notebook
Source of the issue might be that I'm on the German Amazon account, so maybe the code to recognize if I'm on the Notebook page is checking some elements that are localized?

Would be great if this could be fixed, as I'm highly interested in using it for copying my notes into markdown.

**Comment by GitMurf** [comment]
Combining to other issue...

Duplicate of #63
