### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by mrcasals** [GitMurf/roam-highlighter#9]
Hi!

Loved the idea! I'm a Firefox user, is there any chance this gets published as a Firefox extension?

Thanks for your work!

**Comment by GitMurf** [comment]
This is on my list of To-Do but to be honest, far down the list. I am going to try and make the Chrome Extension as good/consistent as I can first, then can look into this. Realistically probably won't be for a week or two. I'll keep you posted here though.

**Comment by mrcasals** [comment]
Awesome, thank you very much for you work! 😄

**Comment by GitMurf** [comment]
**From Vladyslav Sitalo:** from skimming the code - I don’t believe you need to do anything chrome specific, as you don’t really use much of the extension stuff.
I think it’d be just defining the highliter.js as content script in manifest and it should just work

**Comment by mrcasals** [comment]
Yay!! Can we expect to have a Firefox version soon-ish then? 😍

**Comment by GitMurf** [comment]
@mrcasals see the below tweet. It’s done but Firefox is being difficult because Roam is closed to Public! I’m working on getting around this though. 


https://twitter.com/shawnpmurphy8/status/1261767090249191424?s=21

**Comment by lkhphuc** [comment]
I installed manually from the .xpi file and it worked great. Please don't hack me though. 
Just joking, thanks a lot.

**Comment by GitMurf** [comment]
@lkhphuc haha I know it is totally unfortunate we have to do it this way for now but Firefox has spoken and won’t let us publish addons until Roam is open beta :(

**Comment by mrcasals** [comment]
Well, it's a nice start anyway! Thanks for your work and time on this! ❤️
